/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warhammerplayersheet;

import java.util.ArrayList;

/**
 *
 * @author Rivs
 */
public class AddAsset extends javax.swing.JFrame {

    /**
     * Creates new form AddAsset
     */
    ArrayList professions, skills, talents, equipment;
    
    public AddAsset(ArrayList professions, ArrayList skills, ArrayList talents, ArrayList equipment) {
        initComponents();
        this.professions = professions;
        this.skills = skills;
        this.talents = talents;
        this.equipment=equipment;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addProfession = new javax.swing.JButton();
        labelAdd = new javax.swing.JLabel();
        addSkill = new javax.swing.JButton();
        AddTalent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj element");
        setResizable(false);

        addProfession.setText("Profesję");
        addProfession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProfessionActionPerformed(evt);
            }
        });

        labelAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdd.setText("Dodaj");

        addSkill.setText("Umiejętność");
        addSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSkillActionPerformed(evt);
            }
        });

        AddTalent.setText("Zdolność");
        AddTalent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTalentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addProfession, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddTalent, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProfession)
                    .addComponent(addSkill)
                    .addComponent(AddTalent)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addProfessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProfessionActionPerformed
        new AddProfession(professions, skills, talents, equipment).setVisible(true);
    }//GEN-LAST:event_addProfessionActionPerformed

    private void addSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSkillActionPerformed
        new AddSkill(skills).setVisible(true);
    }//GEN-LAST:event_addSkillActionPerformed

    private void AddTalentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTalentActionPerformed
        new AddTalent(talents, skills).setVisible(true);
    }//GEN-LAST:event_AddTalentActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTalent;
    private javax.swing.JButton addProfession;
    private javax.swing.JButton addSkill;
    private javax.swing.JLabel labelAdd;
    // End of variables declaration//GEN-END:variables
}
