/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warhammerplayersheet;

import java.util.ArrayList;

/**
 *
 * @author Rivs
 */
public class BrowseAssets extends javax.swing.JFrame {

    /**
     * Creates new form AddAsset
     */
    ArrayList professions, skills, talents, equipment, players;
    public BrowseAssets(ArrayList professions, ArrayList skills, ArrayList talents, ArrayList players) {
        initComponents();
        this.professions = professions;
        this.skills = skills;
        this.talents = talents;
        this.equipment=equipment;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browseProfession = new javax.swing.JButton();
        labelAdd = new javax.swing.JLabel();
        browseSkill = new javax.swing.JButton();
        browseTalent = new javax.swing.JButton();
        browseTalent1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Przeglądaj");
        setResizable(false);

        browseProfession.setText("Profesje");
        browseProfession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseProfessionActionPerformed(evt);
            }
        });

        labelAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdd.setText("Przeglądaj");

        browseSkill.setText("Umiejętności");
        browseSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseSkillActionPerformed(evt);
            }
        });

        browseTalent.setText("Zdolności");

        browseTalent1.setText("Postacie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(browseProfession, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseTalent, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseTalent1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseProfession)
                    .addComponent(browseSkill)
                    .addComponent(browseTalent)
                    .addComponent(browseTalent1)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void browseProfessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseProfessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_browseProfessionActionPerformed

    private void browseSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseSkillActionPerformed
        new BrowseSkills(skills).setVisible(true);
    }//GEN-LAST:event_browseSkillActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseProfession;
    private javax.swing.JButton browseSkill;
    private javax.swing.JButton browseTalent;
    private javax.swing.JButton browseTalent1;
    private javax.swing.JLabel labelAdd;
    // End of variables declaration//GEN-END:variables
}
