/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warhammerplayersheet;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListModel;
import javax.swing.text.BadLocationException;

/**
 *
 * @author Rivs
 */
public class BrowseProfession extends javax.swing.JFrame {

    /**
     * Creates new form AddProfession
     */
    ArrayList skills, talents, equipment;
    ArrayList<Profession> professions;
    
    
    Equipment[] addedEq;    
    DefaultListModel tempAddedEq = new DefaultListModel<Equipment>();
    
    Skill[] addedSkills;    
    DefaultListModel tempAddedSkills = new DefaultListModel<Skill>();
    
    Talent[] addedTalents;    
    DefaultListModel tempAddedTalents = new DefaultListModel<Talent>();
    
    Profession[] addedEntries;    
    DefaultListModel tempAddedEntries = new DefaultListModel<Profession>();
    
    Profession[] addedExits;    
    DefaultListModel tempAddedExits = new DefaultListModel<Profession>();
    
    
    
    public BrowseProfession(ArrayList professions, ArrayList skills, ArrayList talents, ArrayList equipment) {
        initComponents();
        this.professions=professions;
        this.skills=skills;
        this.talents=talents;
        this.equipment=equipment;
        jComboBox1.addItem("<Pusty>");        
        if(!professions.isEmpty())
        {
            jComboBox1.setModel(new DefaultComboBoxModel(professions.toArray()));
            jComboBox1.setSelectedIndex(0);
            
            Profession temp = (Profession)jComboBox1.getSelectedItem();
            
            addedSkills= temp.getSkills();
            addedTalents = temp.getTalents();
            addedEntries = temp.getEntries();
            addedExits = temp.getExits();
            addedEq = temp.getEquipment();
            
            try{
                arrayToModel(tempAddedSkills, addedSkills);
            }catch(NullPointerException e)
            {
                
            }
            jList2.setModel(tempAddedSkills);  

            try{
                arrayToModel(tempAddedTalents, addedTalents);
            }catch(NullPointerException e)
            {
                
            }
            
            jList4.setModel(tempAddedTalents); 

            try{
                arrayToModel(tempAddedEntries, addedEntries);
            }catch(NullPointerException e)
            {
                
            }
            jList5.setModel(tempAddedEntries);
            
            try{
                arrayToModel(tempAddedExits, addedExits);
            }catch(NullPointerException e)
            {
                
            }
            jList6.setModel(tempAddedExits);
        }
        
        
    }
    void arrayToModel(DefaultListModel model, ArrayList array)
    {
        if(array.isEmpty())
        {
            return;
        }
        for(int i=0; i<array.size() ; i++)
        {
            model.addElement(array.get(i));
        }
    }
    void arrayToModel(DefaultListModel model, Object[] array)
    {        
        if(array.equals(null))
        {
            return;
        }
        for(int i=0; i<array.length ; i++)
        {
            model.addElement(array[i]);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        wwfield = new javax.swing.JTextField();
        usfield = new javax.swing.JTextField();
        kfield = new javax.swing.JTextField();
        odpfield = new javax.swing.JTextField();
        ogdfield = new javax.swing.JTextField();
        zrfield = new javax.swing.JTextField();
        intfield = new javax.swing.JTextField();
        swfield = new javax.swing.JTextField();
        pofield = new javax.swing.JTextField();
        ppfield = new javax.swing.JTextField();
        szfield = new javax.swing.JTextField();
        magfield = new javax.swing.JTextField();
        afield = new javax.swing.JTextField();
        zywfield = new javax.swing.JTextField();
        sfield = new javax.swing.JTextField();
        wtfield = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodawanie profesji");
        setResizable(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("Opis profesji");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        wwfield.setEditable(false);
        wwfield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        wwfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wwfield.setToolTipText("Walka Wręcz");

        usfield.setEditable(false);
        usfield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        usfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usfield.setToolTipText("Umiejętności Strzeleckie");

        kfield.setEditable(false);
        kfield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        kfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kfield.setToolTipText("Krzepa");

        odpfield.setEditable(false);
        odpfield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        odpfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        odpfield.setToolTipText("Odporność");

        ogdfield.setEditable(false);
        ogdfield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        ogdfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ogdfield.setToolTipText("Ogłada");

        zrfield.setEditable(false);
        zrfield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        zrfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        zrfield.setToolTipText("Zręczność");

        intfield.setEditable(false);
        intfield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        intfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        intfield.setToolTipText("Inteligencja");

        swfield.setEditable(false);
        swfield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        swfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        swfield.setToolTipText("Siłą woli");

        pofield.setEditable(false);
        pofield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        pofield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pofield.setToolTipText("Punkty Obłędu");

        ppfield.setEditable(false);
        ppfield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        ppfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ppfield.setToolTipText("Punkty Przeznaczenia");

        szfield.setEditable(false);
        szfield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        szfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        szfield.setToolTipText("Szybkość");

        magfield.setEditable(false);
        magfield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        magfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        magfield.setToolTipText("Magia");

        afield.setEditable(false);
        afield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        afield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        afield.setToolTipText("Ataki");

        zywfield.setEditable(false);
        zywfield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        zywfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        zywfield.setToolTipText("Żywotność");

        sfield.setEditable(false);
        sfield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        sfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sfield.setToolTipText("Siła");

        wtfield.setEditable(false);
        wtfield.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        wtfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wtfield.setToolTipText("Wytrzymałość");

        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jList2);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Umiejętności");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton3.setText("Edytuj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Zdolności");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jList4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(jList4);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Profesje wyjścia");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Profesje wejścia");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane6.setViewportView(jList5);

        jScrollPane7.setViewportView(jList6);

        jButton6.setText("Usuń");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Rodzaj profesji");
        jLabel5.setToolTipText("Rodzaj profesji");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(afield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(zywfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(wtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(szfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(magfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pofield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ppfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(wwfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(usfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(odpfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(zrfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(intfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(swfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ogdfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wwfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odpfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zrfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(swfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ogdfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(afield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zywfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(szfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(magfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pofield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ppfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Object[] options = {"Sure", "Yamete!"};
        if(JOptionPane.showOptionDialog(null, "Chcesz edytować?", "Edytowanie elementu", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, null)==0)
        {
            AddProfession editWindow = new AddProfession(professions, skills, talents, equipment);
            editWindow.setVisible(true);
            editWindow.loadProfession(((Profession)jComboBox1.getSelectedItem()).getName());  
            editWindow.getjTextField1().setEnabled(false);
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    void saveLists()
    {
        addedSkills = new Skill[tempAddedSkills.getSize()];
        for(int i=0; i<tempAddedSkills.getSize() ; i++)
        {
            addedSkills[i]=((Skill)tempAddedSkills.get(i));
        }
        addedTalents = new Talent[tempAddedTalents.getSize()];
        for(int i=0; i<tempAddedTalents.getSize() ; i++)
        {
            addedTalents[i]=((Talent)tempAddedTalents.get(i));
        } 
        addedEq = new Equipment[tempAddedEq.getSize()];
        for(int i=0; i<tempAddedEq.getSize() ; i++)
        {
            addedEq[i]=((Equipment)tempAddedEq.get(i));
        }      
        addedExits = new Profession[tempAddedExits.getSize()];
        for(int i=0; i<tempAddedExits.getSize() ; i++)
        {
            addedExits[i]=((Profession)tempAddedExits.get(i));
        }
        addedEntries = new Profession[tempAddedEntries.getSize()];
        for(int i=0; i<tempAddedEntries.getSize() ; i++)
        {
            addedEntries[i]=((Profession)tempAddedEntries.get(i));
        }
        addedExits = new Profession[tempAddedExits.getSize()];
        for(int i=0; i<tempAddedExits.getSize() ; i++)
        {
            addedExits[i]=((Profession)tempAddedExits.get(i));
        }
    }
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(PlayerSheet.yesno())
        {
            professions.remove((Profession)jComboBox1.getSelectedItem());
        }
        this.dispose();
        new BrowseProfession(professions, skills, talents, equipment).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem().equals("<Pusty>"))
        {
            return ;
        }
        Profession temp = (Profession)jComboBox1.getSelectedItem();
        jTextArea1.setText(temp.getDescription());
        
        
        wwfield.setText  (temp.getStats().getWW()==0?"":""+temp.getStats().getWW());
        usfield.setText  (temp.getStats().getUS()==0?"":""+temp.getStats().getUS());
        kfield.setText   (temp.getStats().getK()==0?"":""+temp.getStats().getK());
        odpfield.setText (temp.getStats().getODP()==0?"":""+temp.getStats().getODP());
        ogdfield.setText (temp.getStats().getOGD()==0?"":""+temp.getStats().getOGD());
        zrfield.setText  (temp.getStats().getZR()==0?"":""+temp.getStats().getZR());
        intfield.setText (temp.getStats().getINT()==0?"":""+temp.getStats().getINT());
        swfield.setText  (temp.getStats().getSW()==0?"":""+temp.getStats().getSW());
        pofield.setText  (temp.getStats().getPO()==0?"":""+temp.getStats().getPO());
        ppfield.setText  (temp.getStats().getPP()==0?"":""+temp.getStats().getPP());
        szfield.setText  (temp.getStats().getSZ()==0?"":""+temp.getStats().getSZ());
        magfield.setText (temp.getStats().getMAG()==0?"":""+temp.getStats().getMAG());
        afield.setText   (temp.getStats().getA()==0?"":""+temp.getStats().getA());
        zywfield.setText (temp.getStats().getZYW()==0?"":""+temp.getStats().getZYW());
        sfield.setText   (temp.getStats().getS()==0?"":""+temp.getStats().getS());
        wtfield.setText  (temp.getStats().getWT()==0?"":""+temp.getStats().getWT());
        
        jLabel5.setText(temp.advanced());
        
        try{
                arrayToModel(tempAddedSkills, addedSkills);
            }catch(NullPointerException e)
            {
                System.out.println("Brak skilli");
            }
            jList2.setModel(tempAddedSkills);  

            try{
                arrayToModel(tempAddedTalents, addedTalents);
            }catch(NullPointerException e)
            {
                System.out.println("Brak talentów");
            }
            
            jList4.setModel(tempAddedTalents); 

            try{
                arrayToModel(tempAddedEntries, addedEntries);
            }catch(NullPointerException e)
            {
                System.out.println("Brak wejściówek");
            }
            jList5.setModel(tempAddedEntries);
            
            try{
                arrayToModel(tempAddedExits, addedExits);
            }catch(NullPointerException e)
            {
                System.out.println("Brak wyjściówek");
            }
            jList6.setModel(tempAddedExits);
        
    }//GEN-LAST:event_jComboBox1ActionPerformed
    void fieldToList(DefaultListModel<Profession> targetList, JTextField text)
    {   
        for(int i=0 ; i<targetList.getSize() ; i++)
        {            
            if(targetList.getElementAt(i).getName().equals(text.getText()))
            {
                JOptionPane.showMessageDialog(this, "Taka profesja jest już dodana", "Błąd", JOptionPane.ERROR_MESSAGE);
                text.setText("");
                return;
            }
        }        
        for(int i=0 ; i<professions.size() ; i++)
        {
            if(professions.get(i).getName().equals(text.getText()))
            {
                targetList.addElement(professions.get(i));
                text.setText("");
                return;
            }            
        }
        Object[] options = {"Oui", "Non"};        
        if(JOptionPane.showOptionDialog(null, "Brak profesji w bazie. Utworzyć?", "Nie znaleziono profesji", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, null)==0)
        {
            Profession tempProf = new Profession(text.getText());
            professions.add(tempProf);
            targetList.addElement(tempProf);
        }
        text.setText("");
    }
    void listToList(JList<String> jl1, JList<String> jl2, DefaultListModel targetList, DefaultListModel initialList )
    {
        int index;
        try
        {
        index = jl1.getSelectedIndex();        
        targetList.addElement(initialList.get(index));
        }catch(ArrayIndexOutOfBoundsException e)
        {
            System.out.println("Brakło skilli.");
            return;
        }
        initialList.remove(index);        
    }
    void modelToArray(DefaultListModel model, ArrayList array)
    {
        for(int i=0; i<model.getSize() ; i++)
        {
            array.add(model.get(i));
        }            
    }
    
    /**
     * @param args the command line arguments
     */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField afield;
    private javax.swing.JTextField intfield;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField kfield;
    private javax.swing.JTextField magfield;
    private javax.swing.JTextField odpfield;
    private javax.swing.JTextField ogdfield;
    private javax.swing.JTextField pofield;
    private javax.swing.JTextField ppfield;
    private javax.swing.JTextField sfield;
    private javax.swing.JTextField swfield;
    private javax.swing.JTextField szfield;
    private javax.swing.JTextField usfield;
    private javax.swing.JTextField wtfield;
    private javax.swing.JTextField wwfield;
    private javax.swing.JTextField zrfield;
    private javax.swing.JTextField zywfield;
    // End of variables declaration//GEN-END:variables
}
